version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/src/workspace/airflow"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Tokyo"
