name: Setup Python Env

description: Setup Python Env

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

    - run: uv sync --frozen --no-install-project
      shell: bash
