
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - UV_SYSTEM_PYTHON=1
      - UV_PROJECT_ENVIRONMENT=/usr/local
    stdin_open: true
    tty: true
