services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      - PYTHONPATH=/workspace/src
      - UV_SYSTEM_PYTHON=1
      - UV_PROJECT_ENVIRONMENT=/usr/local
    stdin_open: true
    tty: true
    command: sh -c "uv sync && bash"
